### ISSUE TITLE
Invalid bitcode for armv7 when building for IOS in Unity Cloud Build

### ISSUE THREAD

**Issue by jayswebworks** [mixpanel/mixpanel-unity#12] opened 2016-07-14 03:38 UTC
I am getting this error in the logs of my unity cloud build.

[xcode] ld: object contains invalid bitcode: /BUILD_PATH/jays-webworks.minilegends.develop-ios/temp.vN9BFq/Libraries/Plugins/iOS/MixpanelSDK.a(mixpanelCSHARP_wrap.o) for architecture armv7

**Comment by jayswebworks** [comment] 2016-07-14 03:51
The build works when I do it from my local machine.

**Comment by samgreen** [comment] 2016-07-15 18:12
Hi @jayswebworks, we haven't tested with Unity Cloud. We'll take a look and get back to you!

**Comment by jayswebworks** [comment] 2016-07-15 18:31
Hi,

Just an update. 

If I disable bitcode for Unity Cloud build it works.

**Comment by aquaGhost1** [comment] 2016-08-24 16:16
Seeing this here as well. The cloud build must fail based on non bitcode compatible plugins, while we also do not get a fail when archiving locally.

**Comment by aquaGhost1** [comment] 2016-09-20 18:23
@samgreen is there any fix for this coming? Thanks!

**Comment by EIZENHORN91** [comment] 2018-09-29 06:41
Any changes?

**Comment by rocktavious** [comment] 2019-04-13 03:33
@EIZENHORN91 i've done a full rewrite of this library https://github.com/rocktavious/mixpanel-unity and if you are interested in Mixpanel still i'd be interested to know if my fork fixes this issue.  If you are willing to test and the issue is fixed it would go a long way to convincing mixpanel to accept my fork as a PR upstream.

**Comment by EIZENHORN91** [comment] 2019-04-13 10:10
Ohhh it was long time ago 😆

**Closed** 2019-08-09 13:37 UTC
Labels: bug
