### ISSUE TITLE
IL2CPP error building for Android in Unity 2020.2.2f1

### ISSUE THREAD

**Issue by DominatorDuck** [mixpanel/mixpanel-unity#112] opened 2021-01-28 17:02 UTC
After upgrading Unity from version 2020.1.11f1 to version 2020.2.2f1 we were unable to build our game for Android using the same assets, scripts and packages. We narrowed down the issue to MixPanel.

An empty Unity 2020.2.2f1 with mixpanel v2.2.2 building for Android will result in the following IL2CPP error:

`Exception: IL2CPP error (no further information about what managed code was being converted is available)
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

![upload_2021-1-26_21-17-51](https://user-images.githubusercontent.com/11036888/106171618-a7e2bb00-6189-11eb-854f-4aaa2906334e.png)

We were building using the following settings:
- Backend: IL2CPP
- API Level: .NET Standard 2.0
- C++ Configuration: Release

Android Settings:
- Minimum API Level: 4.4 Kitkat (API level 19)
- Target API Level: 10.0 Kitkat (API level 29)

After looking at MixPanel's code I noticed this method (in mixpanel.queue.PendingWriteException): 
![suspect](https://user-images.githubusercontent.com/11036888/106171932-13c52380-618a-11eb-9de2-bb1044d1e252.png)

The SecurityPermission attribute seems to be the troublemaker, since after commenting it we were able to build for Android without problems.

Is the SecurityPermission attribute essential or required? 
Should we solve this issue in some other way?

Thanks for all the input you can provide.

**Comment by arnodekostair** [comment] 2021-03-11 18:36
We are having exactly the same problem with the same error message .. and commenting the `SecurityPermission` attribute seems to fix the problem. (at least we can build for iOS)
What is really strange is that we are using exactly the same version of Mixpanel in another project .. and in that other project we don't encounter any problem building for iOS. (despite using the same Mixpanel classes)

**Comment by arnodekostair** [comment] 2021-03-15 16:19
I think we found the cause of the problem: 
In previous Unity version, in ProjectSettings,asset, setting the usage of ApiCompatibilityLevel to .NET 4 was being written as "apiCompatibilityLevalPerPlatform:  iPhone: 3" . But in recent Unity versions, it is being written "apiCompatibilityLevalPerPlatform:  iOS: 3". 
We manually edit ProjectSettings.asset so that we have both "iOS: 3" and "iPhone: 3", and we don't have that error anymore when building for iOS. 
I don't know what is happening behind the hood but that change in ProjectSettings.asset fixed the problem.

**Comment by canyousayyes** [comment] 2021-05-21 07:38
We encountered the exact problem when building Android (Unity 2020.3.4f1, IL2CPP, .Net Standard 2.0) and commenting out the line like @arnodekostair said would fix this issue.

Checking the .NET documentation, the `SecurityPermission` class is already deprecated: https://docs.microsoft.com/en-us/dotnet/api/system.security.permissions.securitypermission?view=net-5.0

I think Mixpanel should fix this problem in order to maintain .NET Standard 2.0 compatibility.

**Comment by NaturalLam** [comment] 2021-06-17 22:33
Any plan to upgrade to support .NET Standard 2.0? @zihejia

**Comment by TravisC1** [comment] 2021-07-13 03:39
We also are experiencing this issue. Unity 2020.3.4f1. Commenting out line 87 of `PersistentQueueUtils.cs` fixed the build issue as above but this means we can't use the Unity Package Manager and will need to include the package in the repo instead as we can't apply this fix otherwise. 

Would be good to have someone from Mixpanel confirm that:
1) This fix wont affect the plugin's functionality 
2) Plans on resolving this issue in a future release so we can use the package manager.

**Closed** 2021-10-21 17:52 UTC

**Comment by Baba-Lucifer** [comment] 2022-08-10 17:47
Same issue in 2021.3.6

C:\Program Files\Unity\Hub\Editor\2021.3.6f1\Editor\Data\il2cpp\build\deploy\il2cpp.exe --convert-to-cpp --assembly=Library/Bee/artifacts/Android/ManagedStripped/Assembly-CSharp-firstpass.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/Assembly-CSharp.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/Mono.Security.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/mscorlib.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/ProBuilderCore-Unity5.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/System.Configuration.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/System.Core.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/System.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/System.Xml.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.AIModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.AndroidJNIModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.AnimationModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.AssetBundleModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.AudioModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.ClothModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.CoreModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.DirectorModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.GridModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.ImageConversionModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.IMGUIModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.InputLegacyModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.InputModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.ParticlesLegacyModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.ParticleSystemModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.Physics2DModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.PhysicsModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.SharedInternalsModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.SpriteShapeModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.SubsystemsModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.TerrainModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.TerrainPhysicsModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.TextCoreFontEngineModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.TextCoreTextEngineModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.TextRenderingModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.TilemapModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.UI.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.UIElementsModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.UIElementsNativeModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.UIModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.UnityAnalyticsModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.UnityWebRequestModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.VehiclesModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.VFXModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.VideoModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.VRModule.dll --assembly=Library/Bee/artifacts/Android/ManagedStripped/UnityEngine.XRModule.dll --data-folder=Z:/Meta/highwaytruckoffrad/highway truck offroad hill driving/Library/Bee/artifacts/Android/il2cppOutput/data --generatedcppdir=Z:/Meta/highwaytruckoffrad/highway truck offroad hill driving/Library/Bee/artifacts/Android/il2cppOutput/cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile=unityaot-linux --profiler-report --profiler-output-file=Z:/Meta/highwaytruckoffrad/highway truck offroad hill driving/Library/Bee/artifacts/il2cpp_conv_oyxw.traceevents --print-command-line
Error: IL2CPP error (no further information about what managed code was being converted is available)
System.AggregateException: One or more errors occurred. (Found a method reference we cannot resolve to a method definition: System.Void UnityEngine.Scripting.GeneratedByOldBindingsGeneratorAttribute::.ctor())
 ---> System.InvalidOperationException: Found a method reference we cannot resolve to a method definition: System.Void UnityEngine.Scripting.GeneratedByOldBindingsGeneratorAttribute::.ctor()
   at Unity.IL2CPP.DataModel.BuildLogic.MethodReferenceResolver.ResolveMethodReference(TypeContext context, UnderConstructionMethodReferenceRepository repository, CecilSourcedAssemblyData assemblyData, MethodReference methodReference, Dictionary`2 mapping)
   at Unity.IL2CPP.DataModel.BuildLogic.MethodReferenceResolver.ResolveAssemblyMethodReferences(TypeContext context, UnderConstructionMethodReferenceRepository repository, CecilSourcedAssemblyData assemblyDef, ReadOnlyHashSet`1 methodReferences)
   at Unity.IL2CPP.DataModel.BuildLogic.DataModelBuilder.<>c__DisplayClass14_0.<ResolveReferences>b__0(CecilSourcedAssemblyData data)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Unity.IL2CPP.DataModel.BuildLogic.Utils.ParallelHelpers.ForEach[TSource](IEnumerable`1 source, Action`1 func, Boolean enableSerial)
   at Unity.IL2CPP.DataModel.BuildLogic.DataModelBuilder.Build()
   at Unity.IL2CPP.AssemblyConversion.Phases.InitializePhase.Run(AssemblyConversionContext context)
   at Unity.IL2CPP.AssemblyConversion.Classic.ClassicConverter.Run(AssemblyConversionContext context)
   at Unity.IL2CPP.AssemblyConversion.AssemblyConverter.ConvertAssemblies(AssemblyConversionInputData data, AssemblyConversionParameters parameters, AssemblyConversionInputDataForTopLevelAccess dataForTopLevel)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
